runtime: python39  # Use Python 3.9 runtime

env: standard  # Use the standard environment

instance_class: F1  # Use the smallest, cheapest instance class

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

entrypoint: gunicorn -b :$PORT backend.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "backend.settings"

automatic_scaling:

  min_instances: 1
  max_instances: 5
